### ISSUE TITLE
Volume slider needs styling

### ISSUE THREAD

**Issue by akshat157** [akshat157/meditate-app#12]
The current volume slider (can be seen in the main preview on README.md) is not styled to match the app theme - glassy theme with white strokes around shapes (more or less).

**Comment by yencolon** [comment]
Hi, I can help you with this!

**Comment by akshat157** [comment]
Sure! Go ahead! 😄

**Comment by yencolon** [comment]
Hey, what do you think about using a custom component for the slider? Since it is not displayed in the same way across different browsers

**Comment by akshat157** [comment]
I agree, the default slider is rendered differently across browsers. Your suggestion sounds good, go ahead. 👍

**Comment by yencolon** [comment]
I tried to apply a custom slider using CSS only, but instead, I just installed a component😅, let me know if it is ok for you.
