### ISSUE TITLE
Background transitions are not smooth

### ISSUE THREAD

**Issue by akshat157** [akshat157/meditate-app#13]
The background image transitions can be made smooth. Perhaps like fade effect?
The issue can be noticed when selecting the background image.

**Comment by MrOsta** [comment]
Hey, i am on it,
Just to confirm, am i free to add any library for transitions, like animate.css or wow.js or you like to use native CSS animations?
Thanks.

**Comment by MrOsta** [comment]
or maybe react transition group

**Comment by akshat157** [comment]
Hi!
I haven't thought about it yet. Although, if you think these additions can be used for other improvements as well (you can name a couple of potentials once if you find 'em or simply open another issue), please go ahead as I would prefer to stay as bloatless as possible. 😃

**Comment by MrOsta** [comment]
Perfect, today I'll finish it 😄

**Comment by ashuvssut** [comment]
I want to work on it. please assign me this issue

**Comment by akshat157** [comment]
Go ahead @ashuvssut!
