### ISSUE TITLE
Add a .prettierrc configuration file.

### ISSUE THREAD

**Issue by akshat157** [akshat157/meditate-app#18]
The project lacks a standardized formatting configuration file. Its nothing that a `.prettierrc` Prettier config file cannot fix though!
The following formatting rules required at least. You can add more if you like.

* Use 2 spaces for indentation.
* No terminating semicolons.
* Single quotes for the the JS syntax.

Don't forget to run the formatter for all the files once before creating the PR!

**Comment by Megatank58** [comment]
Hello i would like to work on this

**Comment by akshat157** [comment]
Sure!

**Comment by Megatank58** [comment]
#20 fixes this
