### ISSUE TITLE
Default and active options can be shown explicitly.

### ISSUE THREAD

**Issue by akshat157** [akshat157/meditate-app#2]
The default and any active options from both the lists `time` and `sound` (For time its, `2 Minutes` and for audio, its `Rain`) are not visible in the app explicitly. i.e. Once selected, an option must become an `active` option.

This feature can be added simply by adding an `.active` class in the CSS, having the same properties as `hover` and using this `.active` class to define the default and active behavior of the options.

**Comment by juansimon18** [comment]
Hii @akshat157 can work with this?

**Comment by akshat157** [comment]
Go ahead! :)

**Comment by Glomels** [comment]
#4 
I made a pull request for this, hadn't seen someone wanted to work on it already :(

**Comment by akshat157** [comment]
No worries, I'll review it, if it works, I'll merge it. 😄 This project is still in its infancy, you can create a lot of features even if you couldn't solve an issue in the first place. :v:

**Comment by akshat157** [comment]
#4 Solves this.
