### ISSUE TITLE
Hide UI elements after a few seconds when a user has pressed the play button.

### ISSUE THREAD

**Issue by akshat157** [akshat157/meditate-app#27]
It would be great to have all the UI elements hide after a few seconds when a user has pressed the play button. Kind of like what YouTube's video player does with the controls. This will create a more immersive experience for the user.

**Note:** The hide animation should be such that the opacity slowly decreases to 0. But should appear instantly when the user tries to do any action (moves the mouse or presses any key).

**Comment by akshat157** [comment]
@BobinMathew Sure, go ahead!

**Comment by Parul1923** [comment]
Hi
Can you please assign this issue to me?

**Comment by akshat157** [comment]
#41 solves this issue.
