### ISSUE TITLE
Current UI is not responsive

### ISSUE THREAD

**Issue by akshat157** [akshat157/meditate-app#29]
The current UI does not work well on mobile devices. A responsive UI will be an amazing enhancement to the application.

The basic guidelines include
 - Keeping the circular bar to show the audio seek. (Required)
 - Having dropdowns for the duration and white noise. (Can be changed if you have a better alternative.)
 - Volume slider at the bottom.
 - Background images position centred.
 
I would love to keep the theme (glass like) intact on mobile devices.

**Note:** Do not forget to add a screenshot preview of the UI on mobile and tablet devices in case you create a PR for this issue.

**Comment by ashuvssut** [comment]
> Having dropdowns for the duration and "white noise".

How do you control white noise? I could not find any controller in the webpage that controls white noise. Are you referring to the volume slider?
