### ISSUE TITLE
Stop button missing

### ISSUE THREAD

**Issue by akshat157** [akshat157/meditate-app#3]
The app currently doesn't have a `Stop` button. Although the PlayPause button does the job, it doesn't reset the time back to `00:00`. To do so, currently one has to select any option other than the already selected one.

A stop button can be added to the app using the `react-sound` component and perhaps a custom stop icon (Please use the same file format as that of the PlayPause button).

**Comment by robertbegna** [comment]
hey i'd like to work on this

**Comment by akshat157** [comment]
Sure! :)

**Comment by robertbegna** [comment]
hello,
I'm relatively new to using react, so i'm not sure how to add a button using this library specifically. 
So far, i've added just a regular button with the functionalities (stopping audio, resetting the timer). Hope you will find these changes useful

**Comment by kushalShukla-web** [comment]
may i ? i have great knowledge in react

**Comment by akshat157** [comment]
Go ahead @kushalShukla-web!

**Comment by ashuvssut** [comment]
@akshat157 can you assign me this issue please?
