### ISSUE TITLE
 Update React version

### ISSUE THREAD

**Issue by akshat157** [akshat157/meditate-app#74]
React has gone through several upgrades over the past years. It will be great to have the project have the updated version and updated syntax as well!

**Comment by ahammadabdullah** [comment]
@akshat157 hey i want to work on it. Assign please.

**Comment by yashikabaan** [comment]
@akshat157 Please assign me this, I would like to work on it!

**Comment by ahammadabdullah** [comment]
Thanks. let me start.

**Comment by ahammadabdullah** [comment]
@akshat157 hey i need a help. Without any changes why I'm seeing like this !? 

![image](https://github.com/user-attachments/assets/679aa9a5-063f-4397-ba3f-04b70791850c)
